export const propsInListCont = [
   {id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Rental',
     price: 'GHC 1200',
     siteVisit: 'Ghc 200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house12.png','listingImgs/house2.png','listingImgs/house3.png','listingImgs/house4.png','listingImgs/house6.png','listingImgs/house7.png','listingImgs/house8.png','listingImgs/house9.png','listingImgs/house10.png',
      'listingImgs/house11.png','listingImgs/house12.png','listingImgs/house13.png','listingImgs/house14.png','listingImgs/hoouse15.png','house5.png'
     ],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
} ,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Reserve',
     price: 'GHC 1200',
     siteVisit: 'Ghc 200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'unfurnished apartment located at airport residential for rent ',
     image: ['listingImgs/house2.png','listingImgs/house1.png','listingImgs/house3.png','listingImgs/house4.png','listingImgs/house6.png','listingImgs/house7.png','listingImgs/house8.png','listingImgs/house9.png','listingImgs/house10.png',
      'listingImgs/house11.png','listingImgs/house12.png','listingImgs/house13.png','listingImgs/house14.png','listingImgs/hoouse15.png','house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
    
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'Shortlet',
     dealtype: 'Booking',
     price: 'GHC 1200',
     siteVisit: 'Ghc 200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house2.png','listingImgs/house1.png','listingImgs/house3.png','listingImgs/house4.png','listingImgs/house6.png','listingImgs/house7.png','listingImgs/house8.png','listingImgs/house9.png','listingImgs/house10.png',
      'listingImgs/house11.png','listingImgs/house12.png','listingImgs/house13.png','listingImgs/house14.png','listingImgs/hoouse15.png','house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
    
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'Rental',
     dealtype: 'Booking',
     price: 'GHC 1200',
     siteVisit: 'Ghc 200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'Sale',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
},
{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Shortlet',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
} ,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Sale',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
    
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Shortlet',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
    
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
    image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
},
{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
} ,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
    
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
    
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
},
{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
} ,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
    
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
    
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
},
{id: 1,
    name:'wilwek consult',
     property: 'house',
     dealtype: 'Rental',
     price: 'GHC 4000',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
},
   {id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Rental',
     price: 'GHC 1200',
     siteVisit: 'Ghc 200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house2.png','listingImgs/house1.png','listingImgs/house3.png','listingImgs/house4.png','listingImgs/house6.png','listingImgs/house7.png','listingImgs/house8.png','listingImgs/house9.png','listingImgs/house10.png',
      'listingImgs/house11.png','listingImgs/house12.png','listingImgs/house13.png','listingImgs/house14.png','listingImgs/hoouse15.png','house5.png'
     ],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
} ,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Reserve',
     price: 'GHC 1200',
     siteVisit: 'Ghc 200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'unfurnished apartment located at airport residential for rent ',
     image: ['listingImgs/house2.png','listingImgs/house1.png','listingImgs/house3.png','listingImgs/house4.png','listingImgs/house6.png','listingImgs/house7.png','listingImgs/house8.png','listingImgs/house9.png','listingImgs/house10.png',
      'listingImgs/house11.png','listingImgs/house12.png','listingImgs/house13.png','listingImgs/house14.png','listingImgs/hoouse15.png','house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
    
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'Shortlet',
     dealtype: 'Booking',
     price: 'GHC 1200',
     siteVisit: 'Ghc 200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house2.png','listingImgs/house1.png','listingImgs/house3.png','listingImgs/house4.png','listingImgs/house6.png','listingImgs/house7.png','listingImgs/house8.png','listingImgs/house9.png','listingImgs/house10.png',
      'listingImgs/house11.png','listingImgs/house12.png','listingImgs/house13.png','listingImgs/house14.png','listingImgs/hoouse15.png','house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
    
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'Rental',
     dealtype: 'Booking',
     price: 'GHC 1200',
     siteVisit: 'Ghc 200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'Sale',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
},
{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Shortlet',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
} ,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Sale',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
    
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Shortlet',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
    
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
    image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
},
{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
     image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
} ,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
    
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
    
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
},
{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
} ,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
    
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
    
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
}
,

{id: 1,
    name:'Rife Realty Solutions',
     property: 'house',
     dealtype: 'Booking',
     price: 'GHC 1200',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
},
{id: 1,
    name:'wilwek consult',
     property: 'house',
     dealtype: 'Rental',
     price: 'GHC 4000',
     title: 'Vintage style two bedroom condo fully furnished',
     details: 'fully furnished two medroom house, comes with a parking lot gym and a swimming pool, altra morden minimalist kitchen witch all of its utilities, 24/7 internet access and a playground for your kids,  all utility cost inclusive ',
      image: ['listingImgs/house4.png','listingImgs/house5.png'],
     propDetails: {bed: 4, bath: 4.5, sqft: 4000} ,
     bed: 4,
     bath:4.5,
     sqft:4000,
     verified: false,
     postTimestamp: '3 weeks',
     location:{
    region:'Accra',
    area: 'Madina'},
   
}
]

